language: node_js
node_js: 14
git:
  depth: false
branches:
  only:
    - master

install:
  - yarn

script:
  - yarn build

after_success:
  - cd ./dist
  - git init
  - git add .
  - git commit -m "Build $(date +%Y%m%d%H%M)"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/assholev0/v0.chat.git" master:gh-pages
